version: '3.7'
services:
  mysql:
    image: mysql:5.7
    container_name: mysql-${APP_NAME}
    command: ["--default-authentication-plugin=mysql_native_password"]
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - mysql

  php-fpm:
    container_name: php-fpm-${APP_NAME}
    build: ./docker/php-fpm
    ports:
      - ${PHP_FPM_PORT}:9001
    volumes:
      - ./${APP_NAME}:/app/:cached
    networks:
      - site
      - mysql
  nginx:
    container_name: nginx-${APP_NAME}
    build: ./docker/nginx
    ports:
      - ${APP_PORT}:80
    depends_on:
      - php-fpm
    networks:
      - site
    volumes:
      - ./${APP_NAME}:/app/:cached

  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-${APP_NAME}
    links:
        - mysql
    restart: always
    ports:
      - ${PHP_MYADMIN_PORT}:80
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - site
      - mysql

networks:
  site:
  mysql:
volumes:
  db_data: